# Generated by Django 3.0.5 on 2020-05-11 14:17

from django.db import migrations, models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Delivered'), (2, 'Failed'), (3, 'In Queue'), (4, 'Cancelled')], default=3)),
                ('food_id', models.UUIDField(default=uuid.uuid1)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('donor', models.CharField(default='None', max_length=100)),
                ('recipient', models.CharField(default='None', max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('title', models.CharField(default='Help!', max_length=60, null=True)),
                ('give', models.CharField(max_length=100)),
                ('want', models.CharField(default=None, max_length=100)),
                ('method', models.IntegerField(choices=[(0, 'Donation'), (1, 'Trade')], default=0)),
                ('author', models.CharField(max_length=100)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
