# Generated by Django 3.0.5 on 2020-05-17 14:39

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Success'), (2, 'Failed'), (3, 'In Queue')], default=3)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('author', models.CharField(max_length=100)),
                ('accepter', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=60)),
                ('content', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
