# Generated by Django 3.0.5 on 2020-04-27 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 27, 14, 42, 20, 195280, tzinfo=utc), verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='date update'),
        ),
    ]
