# Generated by Django 3.0.5 on 2020-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200429_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.CharField(default='None :(', max_length=100),
        ),
    ]
