# Generated by Django 3.0.5 on 2020-04-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_transaction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='Help!', max_length=60, null=True),
        ),
    ]
