# Generated by Django 3.0.5 on 2020-05-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200430_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='give',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='want',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
