# Generated by Django 3.0.5 on 2020-05-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200501_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Delivered'), (2, 'Failed'), (3, 'In Queue'), (4, 'Cancelled')], default=3),
        ),
    ]
