# Generated by Django 3.0.3 on 2020-05-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20200501_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.IntegerField(choices=[(0, 'Donation'), (1, 'Trade')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='want',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
