# Generated by Django 3.0.5 on 2020-05-01 15:43

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('items', '0008_auto_20200501_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='author',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.IntegerField(choices=[(0, 'Donation'), (1, 'Trade')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='donor',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tags',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='want',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
