# Generated by Django 3.0.5 on 2020-04-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='happiness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.CharField(default='Second Lieutenant', max_length=100),
        ),
    ]
