# Generated by Django 3.0.5 on 2020-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.CharField(default='Layman', max_length=100),
        ),
    ]
