# Generated by Django 3.0.5 on 2020-04-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200426_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='medals',
            field=models.TextField(default=''),
        ),
    ]
