# Generated by Django 3.0.5 on 2020-04-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Delivered'), (2, 'Failed'), (3, 'Inqueue')])),
                ('food_id', models.UUIDField()),
                ('category', models.CharField(max_length=200)),
                ('tags', models.TextField()),
                ('donor', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
    ]
