# Generated by Django 3.0.5 on 2020-04-26 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.UUIDField(default=uuid.uuid1)),
                ('category', models.CharField(default='general', max_length=200)),
                ('tags', models.TextField(blank=True, null=True)),
                ('donor', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
