# Generated by Django 3.0.5 on 2020-04-21 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_transaction',
            name='food_id',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
