# Generated by Django 3.0.5 on 2020-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200421_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_transaction',
            name='category',
            field=models.CharField(default='general', max_length=200),
        ),
        migrations.AlterField(
            model_name='food_transaction',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food_transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Delivered'), (2, 'Failed'), (3, 'In Queue')], default=3),
        ),
        migrations.AlterField(
            model_name='food_transaction',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
